### PR TITLE
DRE_8137 Add a query log murron formatter

### PR DESCRIPTION
**Pull request by ejortegau**
## Description
This PR adds the ability to log queries in a format that can be directly written by the vtgate to the murron rsyslog socket.

This is necessary so that we can continue to log queries from the vtgates nad end up in the datawarehous, without having to modify the pipeline that gets them there.

Notice that this patch is Slack-specific (as is Murron).

The screenshot below shows the message as received by murron, as per `murron-tail` output

image

And this one shows the query in dw:
image

### CODE REVIEW

**Comment by timvaillancourt** [comment]
@ejortegau I think one of the main goals of the recent refactoring of our Vitess fork was to reduce (or hopefully eliminate) cases where we diverge from upstream and add to the burden of maintaining our fork. This is a patch that we'll need to maintain with every release if it is not accepted upstream

It sounds like we want to capture query logs from Vitess. Is it possible to achieve the same end result without diverging from upstream?

cc @tanjinx / @vmogilev for thoughts

**Comment by ejortegau** [comment]
> @ejortegau I think one of the main goals of the recent refactoring of our Vitess fork was to reduce (or hopefully eliminate) cases where we diverge from upstream and add to the burden of maintaining our fork. This is a patch that we'll need to maintain with every release if it is not accepted upstream
> 
> It sounds like we want to capture query logs from Vitess. Is it possible to achieve the same end result without diverging from upstream?
> 
> cc @tanjinx / @vmogilev for thoughts

Hi, @timvaillancourt :

I totally understand the concern. I looked into alternatives, but they would have required to modify the existing pipeline from the vtgate to dw beyond what is, IMHO, within the scope of the bedrock migration. Currently, murron is the only thing doing that process, and it operates both on EC2 and bedrock - Albeit in EC2, we use rsyslog to read the query log file and write out in the format murron expects. In Bedrock there is no rsyslog, hence why we need vtgate to write in murron compatible format.

If we were to adopt/build any other solution, we would likely need to maintain two for as long as we have both bedrock and EC2 vtgates, which might be months. 

FWIW, as per [the docs](https://slack-github.com/slack/docs/blob/master/kubernetes/visibility.md#additional-log-streams), these are the three options to have additional log streams (which is what we have, the vtgate regular log and its query log):

1. Write to file, have a sidecar tailing the file. Then the additional log stream makes it to logstash, but there is nothing taking it to dw. It also requires somehow managing the size of the file. vitess can rotate, but does not get rid of the old logs, so eventually the container will fill up, as there is no logrotate in the pod.
2. Use structured logging. Log to the regular vtgate log also the queries, and differentiate them with a field of type of log. This would require larger vitess modifications, and would also not get the queries to dw.
3. Communicate directly with murron - what was done in this PR.

**Comment by timvaillancourt** [comment]
Thanks for the context @ejortegau

> FWIW, as per [the docs](https://slack-github.com/slack/docs/blob/master/kubernetes/visibility.md#additional-log-streams), these are the three options to have additional log streams (which is what we have, the vtgate regular log and its query log):
> 
> 1. Write the additional log streams to files, have a sidecar tailing the file. Then the additional log stream makes it to logstash as the log of the sidecar, but there is nothing taking it to dw. It also requires somehow managing the size of the file. vitess can rotate, but does not get rid of the old logs, so eventually the container will fill up, as there is no logrotate in the pod.
> 2. Use structured logging. Log to the regular vtgate log also the queries, and differentiate them with a field of type of log. This would require larger vitess modifications, and would also not get the queries to dw.
> 3. Communicate directly with murron - what was done in this PR.

Concerns about diverging and maintenance-burdens aside, my opinion is capturing logs from containers in Kube is a solved problem that shouldn't require a custom solution. If that is difficult to do in our framework I feel we should focus on that drawback as any container under Kube will need to capture logs and that shouldn't be difficult for teams to implement 

I believe the common approach in the Kube world is running [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/)s to capture logs from any container on a Kube host, or sidecars like the 1st option you mentioned. The DaemonSet approach solves the problem much more generically

**Comment by roderickyao** [comment]
DaemonSet is the general mechanism used by k8s to run logging agents. In this case, Murron and other per k8s node binaries are using DaemonSet. In general I think it is tricky to modify Vitess to work with Murron. Any changes to Murron will be on us to maintain.

**Comment by timvaillancourt** [comment]
> With that being said, we could use a sidecar of `rsyslog` that transform the query log just like EC2.

Agreed. My $0.02 is the teams responsible for the Kube framework should provide a low-effort solution that will work generically for various teams so we can focus on getting stuff done 👍

**Comment by ejortegau** [comment]
Hi, @timvaillancourt and @roderickyao:  
> Concerns about diverging and maintenance-burdens aside, my opinion is capturing logs from containers in Kube is a solved problem that shouldn't require a custom solution. If that is difficult to do in our framework I feel we should focus on that drawback as any container under Kube will need to capture logs and that shouldn't be difficult for teams to implement
I believe the common approach in the Kube world is running [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/)s to capture logs from any container on a Kube host, or sidecars like the 1st option you mentioned. The DaemonSet approach solves the problem much more generically

IMHO, the issue here is less about capturing logs and more about ensuring that we don't need to build and maintain a separate means to have those logs parsed, structured and stored  in dw so that they can be consumed. We could build a DaemonSet that did that, but then we are basically duplicating murron. Plus, I am unsure whether bedrock supports defining DaemonSets.

> With that being said, we could use a sidecar of rsyslog that transform the query log just like EC2

We could, but then we would need to also add a `logrotate` sidecar or some other mechanism to ensure that log files don't fill the container (vitess can deal with the rotation but not the removal of old log files). I think it is an antipattern to try run in a pod as many things as we en up running on EC2 - that's more components to manage, upgrade, test, etc. 

I understand the push for running closer to upstream, but as per the docs I linked above, the bedrock team's solution for multiple log streams are the three I mentioned before, and the only one of those that does not require us to build and maintain a new  way to ship the query log to dw is talking to murron. Given that the code of this PR is fairly well isolated from other vitess code, I don't think that it will be hard to apply on upcoming releases; and I suspect that that will be significantly easier than building and maintaining a separate pipeline for getting logs into dw.

That being said, if you both feel strongly about this and think that it is worth delaying the bedrock migration of vtgates until we do that, I am also fine with it. I am just trying to address things in a way that seems compatible with the delivery timelines we have.

**Comment by roderickyao** [comment]
I am fine with a temporary solution. I guess we would also need a feature request to Bedrock to provide something that fill the gap there.

**Review by roderickyao — APPROVED** [review]
LGTM. Mark this as a short term workaround. In the meanwhile, please open a feature request to the Bedrock team to get a long term support.

**Comment by tanjinx** [comment]
yeah, I share the same concerns that Tim said above. The ultimate goal is to no longer maintain our own customized code and work with upstream directly unless there is a compelling reason to do so. 

Logging is a critical component for one service, imho for bedrock, we should design a brand-new framework *in the beginning* instead of tweaking the existing one that ec2 uses. If this is just for prototyping (or temporary phase), then this PR should go into a temporary branch instead of a release branch.

**Pull request closed without merging**
