### PR TITLE
VStreams  NOT_FOUND Error Retries and Omits Tablet

### PR DESCRIPTION
**Pull request by makinje16**
## Description
Currently, vstreams fail as expected when trying to stream from a tablet that is being replaced for _some_ reason. However, when the `NOT_FOUND` error is returned to the vstream client it does not omit the restore tablet from being used during the next retry. This can lead to streams being blocked for multiple hours. 

The reason this is added to our fork instead of committed upstream is because this has been fixed in future versions of Vitess, but, when bringing that fix in, there were many dependencies that caused issues with the merge. This change will be added in order to unblock CDC until we are more caught up with upstream.

## Testing
This change has been in dev over the last several weeks and recently it was [noted](https://slack-pde.slack.com/archives/C01P84R7L02/p1702586748407959) that the `NOT_FOUND` errors have not been in over [4 weeks](https://logstash-dev.tinyspeck.com/app/discover?#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-4w,to:now))&_a=(columns:!(message,host,msg),filters:!(),index:kube,interval:auto,query:(language:lucene,query:'host:%22dbzium-*%22%20AND%20message:*NOT_FOUND*'),sort:!(!('@timestamp',desc)))).
## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by pbibra** [comment]
original discussion for posterity: https://slack-pde.slack.com/archives/C01P84R7L02/p1695329095557079
decision to not re-try on this error upstream: https://github.com/vitessio/vitess/pull/14224#discussion_r1361003113

**Comment by timvaillancourt** [comment]
> when trying to stream from a tablet that is still in Restore

@makinje16 / @pbibra: are we seeing VStreams use `RESTORE` tablets when specifying `RDONLY`+`REPLICA` as the allowed tablet types?

**Comment by pbibra** [comment]
> > when trying to stream from a tablet that is still in Restore
> 
> @makinje16 / @pbibra: are we seeing VStreams use `RESTORE` tablets when specifying `RDONLY`+`REPLICA` as the allowed tablet types?

Sorry to clarify, we're not streaming from a tablet that is still in Restore, we'd be trying to stream from a tablet that's being replaced due to an issue. Since the current tablet picker version does not perform the health check before a tablet is chosen for streaming, we run into this issue.

**Comment by timvaillancourt** [comment]
> Sorry to clarify, we're not streaming from a tablet that is still in Restore, we'd be trying to stream from a tablet that's being replaced due to an issue. Since the current tablet picker version does not perform the health check before a tablet is chosen for streaming, we run into this issue.

Ahh I understand, thanks for clarifying 👍

**Review by pbibra — APPROVED** [review]

**Pull request merged**
